apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slop-tls-cert
  namespace: default
spec:
  secretName: slop-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - slop.cat-herding.net
